#!/bin/sh
# postinst script for sentinella-agent
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package


case "$1" in
    configure)
        # create a sentinella group and user
        if ! grep -q sentinella /etc/passwd; then
                addgroup --system sentinella
                adduser --system --no-create-home --group sentinella
        fi
        mkdir -p /var/log/sentinella
        chown sentinella /var/log/sentinella
        mkdir -p /var/run/sentinella
        chown sentinella /var/run/sentinella
        chmod 644 /etc/logrotate.d/sentinella
        ln -fs /usr/share/python/sentinella/bin/sentinella /usr/local/bin/sentinella
        /usr/share/python/sentinella/bin/sentinella init
        update-rc.d sentinella defaults
        echo "Start the service with"
        echo "\tsudo service sentinella start"

    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
